Sopon/Controllers/OutcomeController.cs
using Sopon.DBAccess;
using Sopon.Library;
using Sopon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Sopon.Controllers
{
    public class OutcomeController : Controller
    {
        public ActionResult Outcome()
        {
            DatabaseAccess dba = new DatabaseAccess();
            var outcomes = dba.GetAllOutcomeDetails();

            return View("OutcomeView", new OutcomeModel(outcomes));
        }

        public ActionResult GoToAddNewOutcomeRecordPage(OutCome newRecord)
        {
            return Redirect("AddOutcomeView");
        }

        public ActionResult HandleAddNewOutcomeRecord(string name, string amount, string unitPrice,
            string count, string date, string desc)
        {
            OutCome rec = new OutCome();
            rec.OutcomeName = name;
            rec.Amout = string.IsNullOrEmpty(amount) ? 0 : Convert.ToInt32(amount);
            rec.GoodsUnitPrice = string.IsNullOrEmpty(unitPrice) ? 0 : Convert.ToDouble(unitPrice);
            rec.GoodsCount = string.IsNullOrEmpty(count) ? 0 : Convert.ToInt32(count);
            rec.CreatedDate = string.IsNullOrEmpty(date) ? DateTime.Now.ToString("yyyy-MM-dd") : date;
            rec.OutcomeDesc = desc;

            DatabaseAccess dba = new DatabaseAccess();

            var result = dba.AddNewOutcomeRecord(rec);
            var outcomes = dba.GetAllOutcomeDetails();

            return View("OutcomeView", new OutcomeModel(outcomes));
        }

        public ActionResult HandleModifyOutcomeRecord(string id, string name, string amount, string unitPrice,
                                                         string count, string date, string desc)
        {
            OutCome rec = new OutCome();
            rec.ID = Convert.ToInt32(id);
            rec.OutcomeName = name;
            rec.Amout = Convert.ToInt32(amount);
            rec.GoodsUnitPrice = Convert.ToDouble(unitPrice);
            rec.GoodsCount = Convert.ToInt32(count);
            rec.CreatedDate = date;
            rec.OutcomeDesc = desc;

            DatabaseAccess dba = new DatabaseAccess();

            var result = dba.UpdateOutcomeRecord(rec);

            var outcomes = dba.GetAllOutcomeDetails();

            return View("OutcomeView", new OutcomeModel(outcomes));
        }

        public ActionResult AddOutcomeView()
        {
            return View();
        }

        public ActionResult UpdateOutcomeView(int id)
        {
            DatabaseAccess dba = new DatabaseAccess();

            var outcome = dba.GetOutcomeBySID(id);

            return View("UpdateOutcomeView", new UpdateOutComeModel(outcome));
        }

        public ActionResult HandleDeleteOutcome(string id)
        {
            DatabaseAccess dba = new DatabaseAccess();

            var res = dba.DeleteOutcomeBySID(id);

            var outcomes = dba.GetAllOutcomeDetails();

            return View("OutcomeView", new OutcomeModel(outcomes));
        }

        [HttpGet]
        public ActionResult Outcome(string outcomeName, string outcomeDesc, string fromDate, string toDate)
        {
            DatabaseAccess dba = new DatabaseAccess();

            var res = dba.GetOutcomeBySearchConditions(outcomeName, outcomeDesc, fromDate, toDate);

            // Clear the ModelState
            ModelState.Clear();

            return View("OutcomeView", new OutcomeModel(res));
        }
    }
}

Sopon/Views/Outcome/AddOutcomeView.cshtml
@using Sopon.Library
@using Sopon.Models
@model OutCome

@section Scripts
{
    <script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.ordertable.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>

    <script>
        $("#form").submit(function (e) {

            var url = '/Outcome/HandleAddNewOutcomeRecord'; // the script where you handle the form input.

            $.ajax({
                type: "POST",
                url: url,
                data: {
                    name: $('#txtOutcomeName').val(),
                    amount: $('#txtAmout').val(),
                    unitPrice: $('#txtGoodsUnitPrice').val(),
                    count: $('#txtGoodsCount').val(),
                    date: $('#txtCreatedDate').val(),
                    desc: $('#txtOutcomeDesc').val()
                },
                //data: $("#form").serialize(), // serializes the form's elements.
                success: function (data) {
                    alert(data); // show response from the php script.
                }
            });

            e.preventDefault(); // avoid to execute the actual submit of the form.
        });

        $(function () {
            $("#txtCreatedDate").datepicker({
                dateFormat: 'yy-mm-dd',
            });
        });
    </script>

    <link href="~/Content/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link href='~/Content/OpenSansFontFamily.css' rel='stylesheet' type='text/css'>
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <style type="text/css">
        body {
            background: #ECF0F1;
            font-family: 'Open Sans' sans-serif;
        }

        .container {
            margin: 150px auto 30px auto;
        }

        h1 {
            margin-bottom: 30px;
        }
    </style>
}


<section>
    <div class="row">
        <div class="col-lg-12">
            <!-- Page Heading -->
            <br />
            <h1 class="page-header" style="font-family:YouYuan">
                新加支出
            </h1>
            <!-- /.row -->
            <div class="row">
                <form role="form" id="form">
                    <div class="form-group">
                        <label class="control-label" for="txtOutcomeName">支出项目</label>
                        <input type="text" class="form-control" id="txtOutcomeName">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtAmout">支出费用</label>
                        <div class="form-group input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" id="txtAmout">
                            <span class="input-group-addon">.00</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtGoodsUnitPrice">物品单价</label>
                        <div class="form-group input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" id="txtGoodsUnitPrice">
                            <span class="input-group-addon">.00</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtGoodsCount">物品数量</label>
                        <input type="text" class="form-control" id="txtGoodsCount">
                    </div>
                    <div class="form-group" id="divDate">
                        <label class="control-label" for="txtCreatedDate">支出时间</label>
                        <input id="txtCreatedDate" class="form-control" style="position: relative; z-index: 100000;" type="text" value="">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtOutcomeDesc">补充说明</label>
                        <input type="text" class="form-control" id="txtOutcomeDesc">
                    </div>
                    <input id="btnAdd" type="submit" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei';width:120px"></input>
                    <button id="btnCancel" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei';width:120px">取消</button>
</form>
            </div>
        </div>
    </div>
</section>

Sopon/Views/Outcome/OutcomeView.cshtml
@using Sopon.Library
@using Sopon.Models
@model OutcomeModel

@section Scripts
{
    <script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.ordertable.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblView').orderTable({ excludeColumns: 6 });

            $("#btnAdd").click(function () {
                window.location = '/Outcome/GoToAddNewOutcomeRecordPage';
            });

            var advSearchPanelHeight = $("#divAdvSearch").css("height");
            $("#divAdvSearch").css("height", "0px");
            $("#btnSwitch").click(function () {
                if ($("#divAdvSearch").css("visibility") != "hidden") {
                    $("#divAdvSearch").css("visibility", "hidden");
                    $("#btnSwitch").text("搜索")
                    $("#divAdvSearch").css("height", "0px");
                }
                else {
                    $("#divAdvSearch").css("visibility", "visible");
                    $("#btnSwitch").text("隐藏")
                    $("#divAdvSearch").css("height", advSearchPanelHeight);
                }
            });

            // nav
            $(function shownav() {
                var a2 = $(".side-nav>li>a");

                for (var i = 0; i < a2.length; i++) {
                    if (a2[i].getAttribute("href") == window.location) {
                        $parent = $(a2[i]).parent("li");
                        $parent.addClass("active");
                        return;
                    }
                }
                $(a2[0]).parent("li").addClass("active");
            })

            var list = $('button[id^=btnModify_]');
            list.each(function () {
                // modify button click event
                $(this).click(function () {
                    var id2Modify = $(this).attr("id").substr(10, $(this).attr("id").length - 10);

                    debugger;
                    $.ajax({
                        url: '/Outcome/UpdateOutcomeView',
                        data: { id: id2Modify },
                        type: "GET",
                        success: function (data) {
                            window.location = '/Outcome/UpdateOutcomeView?id=' + id2Modify;
                        }
                    });
                });
            })


            var listDelBtns = $('button[id^=btnDelete_]');
            listDelBtns.each(function () {
                // modify button click event
                $(this).click(function () {
                    var id2Modify = $(this).attr("id").substr(10, $(this).attr("id").length - 10);

                    debugger;
                    $.ajax({
                        url: '/Outcome/HandleDeleteOutcome',
                        data: { id: id2Modify },
                        type: "POST",
                        success: function (data) {
                            window.location = '/Outcome/Outcome';
                        }
                    });
                });
            })

            $("#btnClear").click(function () {
                $("#txtOutcomeName").val("");
                $("#txtOutcomeDesc").val("");
                $("#txtStart").val("");
                $("#txtEnd").val("");
            });

            $("#btnSearch").click(function () {
                $.ajax({
                    url: '/Outcome/Outcome',
                    data: { outcomeName: $("#txtOutcomeName").val(), outcomeDesc: $("#txtOutcomeDesc").val(), fromDate: $("#txtStart").val(), toDate: $("#txtEnd").val() },
                    type: "GET",
                    success: function (data) {
                        window.location = '/Outcome/Outcome?outcomeName=' + $("#txtOutcomeName").val() + '&outcomeDesc=' + $("#txtOutcomeDesc").val() + '&fromDate=' + $("#txtStart").val() + '&toDate=' + $("#txtEnd").val();
                        //if (data.length > 0)
                        //    $('body').html(data);
                    }
                });
            });


            var outcomeName = getParameterByName('outcomeName');
            var outcomeDesc = getParameterByName('outcomeDesc');
            var fromDate = getParameterByName('fromDate');
            var toDate = getParameterByName('toDate');

            if (outcomeName != '' || outcomeDesc != '' || fromDate != '' || toDate != '') {
                $("#divAdvSearch").css("visibility", "visible");
                $("#btnSwitch").text("隐藏")
                $("#divAdvSearch").css("height", advSearchPanelHeight);
                $("#txtOutcomeName").val(outcomeName);
                $("#txtOutcomeDesc").val(outcomeDesc);
                $("#txtStart").val(fromDate);
                $("#txtEnd").val(toDate);
            }
        });

        function getParameterByName(name) {
            name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                results = regex.exec(location.search);
            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        }

        $(function () {
            $("#txtStart").datepicker({
                dateFormat: 'yy-mm-dd',
            });
        });

        $(function () {
            $("#txtEnd").datepicker({
                dateFormat: 'yy-mm-dd',
            });
        });
    </script>

    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36251023-1']);
        _gaq.push(['_setDomainName', 'jqueryscript.net']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>

    <link href="~/Content/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link href='~/Content/OpenSansFontFamily.css' rel='stylesheet' type='text/css'>
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    @*<link href="~/Content/sb-admin.css" rel="stylesheet">*@
    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <style type="text/css">
        body {
            background: #ECF0F1;
            font-family: 'Open Sans' sans-serif;
        }

        .container {
            margin: 150px auto 30px auto;
        }

        h1 {
            margin-bottom: 30px;
        }

        .order-table {
            cursor: pointer;
        }

            .order-table:after, .order-table--asc:after, .order-table--desc:after {
                font-size: .7em;
                width: 1em;
                display: inline-block;
            }

            .order-table:after {
                content: '▲▼';
            }

        .order-table--asc:after {
            content: '▲';
        }

        .order-table--desc:after {
            content: '▼';
        }

        #overlay {
            visibility: hidden;
            position: absolute;
            background-color: gray;
            opacity: 0.4;
            filter: alpha(opacity=40); /*For IE8 and earlier*/
            left: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            text-align: center;
            z-index: 1000;
        }

            #overlay div {
                width: 300px;
                margin: 150px auto;
                background-color: #fff;
                opacity: 1;
                filter: alpha(opacity=100); /*For IE8 and earlier*/
                border: 1px solid #000;
                padding: 15px;
                text-align: center;
                color: black;
            }
    </style>
}


<section>
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <br />
            <table>
                <tr>
                    <td width="60%">
                        <h1 class="page-header" style="font-family:YouYuan">
                            支出明细
                        </h1>
                    </td>
                    <td>
                        <button id="btnAdd" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei';width:120px">添加</button>
                    </td>
                    <td>
                        <button id="btnSwitch" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei' ;width:120px">搜索</button>
                    </td>
                    <td width="7%">
                        <button id="btnExport" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei' ;width:120px">导出</button>
                    </td>
                </tr>
            </table>
            @*@using (Html.BeginForm("HandleSearch", "Outcome", FormMethod.Get, new { id = "SearchForm" }))
                {*@
            <div id="divAdvSearch" style="visibility:hidden">
                <span class="form-group">
                    <label class="control-label" for="txtOutcomeName">支出项目</label>
                    <input type="text" class="form-control" id="txtOutcomeName">
                </span>
                <span class="form-group">
                    <label class="control-label" for="txtOutcomeDesc">支出说明</label>
                    <input type="text" class="form-control" id="txtOutcomeDesc">
                </span>
                <span class="form-group">
                    <label class="control-label" for="txtStart">从</label>
                    <input id="txtStart" class="form-control" style="position: relative; z-index: 100000;" type="text" value="">
                </span>
                <span class="form-group">
                    <label class="control-label" for="txtEnd">到</label>
                    <input id="txtEnd" class="form-control" style="position: relative; z-index: 100000;" type="text" value="">
                </span>
                <br style="height:2px" />
                <span class="form-group" style="margin-top:3px">
                    <button id="btnSearch" type="submit" class="btn btn-lg btn-primary" style="font-family: 'Microsoft YaHei';width:120px">提交</button>
                    <button id="btnClear" type="button" class="btn btn-lg btn-primary" style="font-family: 'Microsoft YaHei';width:120px">清空</button>
                </span>
            </div>
            @* } *@
            @if (Model.OutcomeDetails != null)
            {
                double sumAmount = 0;
                int sumCount = 0;
                <br style="height:2px" />
                <div class="panel panel-yellow" style="border-color: #f0ad4e;">
                    <div class="panel-heading">
                        <h3 class="panel-title">支出详单</h3>
                    </div>
                    <div class="panel-body">
                        <table id="tblView" class="table table-striped">

                            <thead>
                                <tr>
                                    <th>支出项目</th>
                                    <th>支出费用</th>
                                    <th>物品单价</th>
                                    <th>物品数量</th>
                                    <th>支出时间</th>
                                    <th>补充说明</th>
                                    <th>更多操作</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (OutCome item in Model.OutcomeDetails)
                                {
                                    <tr class="success">
                                        <td>@item.OutcomeName</td>
                                        <td>@item.Amout</td>
                                        <td>@item.GoodsUnitPrice</td>
                                        <td>@item.GoodsCount</td>
                                        <td>@item.CreatedDate</td>
                                        <td>@item.OutcomeDesc</td>
                                        <td>
                                            <button type="button" id='btnModify_@item.ID' class="btn btn-sm btn-warning">修改</button>
                                            <button type="button" id='btnDelete_@item.ID' class="btn btn-sm btn-danger">删除</button>
                                        </td>
                                    </tr>
                                    sumAmount += @item.Amout;
                                    sumCount += @item.GoodsCount;
                                }
                            </tbody>

                        </table>
                        <table>
                            <tr class="success">
                                <td style="font-weight:bold; text-align: right">总计: @sumAmount 元</td>
                            </tr>
                        </table>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<div id="overlay">
    <div>
        <p>Processing...</p>
    </div>
</div>

Sopon/Views/Outcome/UpdateOutcomeView.cshtml
@using Sopon.Library
@using Sopon.Models
@model UpdateOutComeModel

@section Scripts
{
    <script src="~/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.ordertable.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>

    <script>
        $("#btnUpdate").click(function (e) {
            var url = '/Outcome/HandleModifyOutcomeRecord'; // the script where you handle the form input.

            $.ajax({
                type: "POST",
                url: url,
                data: {
                    id: $('#txtSID').val(),
                    name: $('#txtOutcomeName').val(),
                    amount: $('#txtAmout').val(),
                    unitPrice: $('#txtGoodsUnitPrice').val(),
                    count: $('#txtGoodsCount').val(),
                    date: $('#txtCreatedDate').val(),
                    desc: $('#txtOutcomeDesc').val()
                },
                //data: $("#form").serialize(), // serializes the form's elements.
                success: function (data) {
                    window.location = '/Outcome/Outcome';
                },
                error: function (data) {
                    alert("Failed to update the record.");
                }
            });
        });

        $("#btnCancel").click(function (e) {
            window.location = '/Outcome/Outcome';
        });
        $(function () {
            $("#txtCreatedDate").datepicker({
                dateFormat: 'yy-mm-dd',
            });
        });
    </script>

    <link href="~/Content/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link href='~/Content/OpenSansFontFamily.css' rel='stylesheet' type='text/css'>
    <link href="~/Content/Bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <style type="text/css">
        body {
            background: #ECF0F1;
            font-family: 'Open Sans' sans-serif;
        }

        .container {
            margin: 150px auto 30px auto;
        }

        h1 {
            margin-bottom: 30px;
        }
    </style>
}


<section>
    <div class="row">
        <div class="col-lg-12">
            <!-- Page Heading -->
            <br />
            <h1 class="page-header" style="font-family:YouYuan">
                修改支出
            </h1>
            <!-- /.row -->
            <div class="row">
                <form role="form" id="form">
                    <input type="hidden" class="form-control" id="txtSID" value="@Model.ID">
                    <div class="form-group">
                        <label class="control-label" for="txtOutcomeName">支出项目</label>
                        <input type="text" class="form-control" id="txtOutcomeName" value="@Model.OutcomeName">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtAmout">支出费用</label>
                        <div class="form-group input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" id="txtAmout" value="@Model.Amout">
                            <span class="input-group-addon">.00</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtGoodsUnitPrice">物品单价</label>
                        <div class="form-group input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" id="txtGoodsUnitPrice" value="@Model.GoodsUnitPrice">
                            <span class="input-group-addon">.00</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtGoodsCount">物品数量</label>
                        <input type="text" class="form-control" id="txtGoodsCount" value="@Model.GoodsCount">
                    </div>
                    <div class="form-group" id="divDate">
                        <label class="control-label" for="txtCreatedDate">支出时间</label>
                        <input id="txtCreatedDate" class="form-control" style="position: relative; z-index: 100000;" type="text"
                               value="@Model.CreatedDate">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="txtOutcomeDesc">补充说明</label>
                        <input type="text" class="form-control" id="txtOutcomeDesc" value="@Model.OutcomeDesc">
                    </div>
                    <button id="btnUpdate" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei';width:120px">更新</button>
                    <button id="btnCancel" type="button" class="btn btn-lg btn-success" style="font-family: 'Microsoft YaHei';width:120px">取消</button>
                </form>
            </div>
        </div>
    </div>
</section>